highlighter: rouge
markdown: kramdown
permalink: /:categories/:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true

url: http://andersonvom.github.io/
title: Erin and Anderson are getting married soon
author: Anderson Mesquita
description: Things to know about the big day
email: andersonvom+erinkcompton ((@@)) gmail.com
google_analytics: UA-31347952-3

defaults:
  - scope:
      path: ""
    values:
      layout: home
  # I can't seem to make this work :(
  # - scope:
  # -   path: en
  # -   type: posts
  # - values:
  # -   categories: en
  # - scope:
  # -   path: pt
  # -   type: posts
  # - values:
  # -   categories: pt
